/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.exascience.formats.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Impact { 
  HIGH, MODERATE, LOW, MODIFIER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Impact\",\"namespace\":\"org.exascience.formats.avro\",\"symbols\":[\"HIGH\",\"MODERATE\",\"LOW\",\"MODIFIER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
